# vim: ft=yaml ts=2:
---

- name: set OS specific variables
  include_vars:
    file: "{{ ansible_distribution }}.yml"

- debug: var=scl
  tags:
    - never
    - debug

- name: scl does exist
  package:
    name: "{{ scl.release }}"
    state: present
